### ISSUE TITLE
Database Creation failed.

### ISSUE THREAD

**Issue by Aeyzaz** [DrewDahlman/headless-wordpress#5]
after restarting the containers i get the following message 

```
wordpress_1  | => Create database 'wordpress'... 
wordpress_1  | => ERROR (Line 87): Database creation failed.
```

**Comment by DrewDahlman** [comment]
Hmm try running `docker-compose rm` or `docker-compose build` seems like maybe there was an issue with the initial setup.

**Comment by Aeyzaz** [comment]
First time it works great  but if i stop the containers and run them again it throws this error because run.sh runs every time.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DrewDahlman** [comment]
The run.sh runs everytime because it has to check for if it needs to set
things up and also starts apache and such. that leads me to think that
maybe the containers aren't being stopped correctly. Are you running
docker-compose down ?

**Comment by Aeyzaz** [comment]
Yes,  i tried docker-compose down and docker-compose stop both have the same results.

This is happening because second time when it tries to create a database 'wordpress' its already there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DrewDahlman** [comment]
Right and there is a check in place that it skips if the db exists https://github.com/DrewDahlman/headless-wordpress/blob/master/wordpress/docker/run.sh#L82-L114 this failing leads me to think there is something odd with the setup. Try `docker-compose down -v` which will nuke the volumes, I believe that's where this issue is coming from.
